"""
Django settings for dcrm project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*t=uff45kt0&v9jv7kt34smsw7euiz_x*ahyc78e&rmg#zw$h%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Cambia a False en producción

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    "django_bootstrap5",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agendamiento',
        'HOST':'host.docker.internal',
        'USER':'root',
        'PORT':'3306',
        'PASSWORD':'',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es' # Cambia a 'es' para español

TIME_ZONE = 'America/Bogota' # Cambia a tu zona horaria local

USE_I18N = True # Habilita la internacionalización

USE_TZ = True # Habilita el uso de zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'# Cambia a 'static/' para servir archivos estáticos desde la carpeta 'static' en tu proyecto

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# configuracion de seguridad de django como jwt, cookies,sesiones, csrf,xss etc. se pueden agregar aquí
#xss protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True # Protege contra ataques de tipo MIME sniffing

# CLicjackjacking protection
X_FRAME_OPTIONS = 'DENY' # Evita que tu sitio sea cargado en un iframe

# referrer policy
SECURE_REFERER_POLICY = 'same-origin' # Solo envía el referer a tu propio dominio

# CSRF protection
CSRF_COOKIE_SECURE = True # Asegura que la cookie CSRF solo se envíe a través de HTTPS
CSRF_COOKIE_HTTPONLY = True # Evita que la cookie CSRF sea accesible a través de JavaScript

CSRF_COOKIE_SESSION = True # Almacena la cookie CSRF en la sesión en lugar de en una cookie separada

# Session security
SESSION_COOKIE_SECURE = True # Asegura que la cookie de sesión solo se envíe a través de HTTPS
SESSION_COOKIE_HTTPONLY = True # Evita que la cookie de sesión sea accesible a través de JavaScript

SESSION_COOKIE_SAME_SITE = 'Lax' # Protege contra ataques CSRF al limitar el envío de cookies a solicitudes del mismo sitio

SESSION_COOKIE_AGE = 300 # Expira la sesión después de 10 segundos de inactividad (ajusta según tus necesidades)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Expira la sesión al cerrar el navegador    
SESSION_SAVE_EVERY_REQUEST = True # Guarda la sesión en cada solicitud para actualizar el tiempo de expiración

