# Generated by Django 4.2.30 on 2026-06-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id_agendamiento', models.AutoField(primary_key=True, serialize=False)),
                ('agendador', models.CharField(max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
