# Generated by Django 4.2.30 on 2026-06-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_shedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shedule',
            new_name='schedule',
        ),
    ]
